language: node_js
node_js:
  - '0.10'
env:
  global:
    secure: GL6DbMjI5B0JGmyx69spvdt+/pzazjcux2qvHHAVlVpgIgv13IEJ0AY98A1lUeoYZjI5zLRf2eoULdo6WO35VBtp8IgjMxi0vSlwBFHKO9yoyPkfsoMMBlQnefnBQBgyk7JkY3euVcYtEUVf+ghz14d9Bm63n64JCCXrMu0RblM=

branches:
  only:
    - master

before_script:
  - npm install -g bower
  - bower install
  - git config --global user.email "ngmaterial@googlegroups.com"
  - git config --global user.name "ngMaterial Bot"

script:
  - gulp karma --browsers=PhantomJS
  - ./scripts/travis-build-init.sh --sha=$TRAVIS_COMMIT

notifications:
  flowdock: ca58afe1354053b15fe75a763138829d
